name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

        # build command should be set in package.json scripts as: "build": "tsc"
      - name: Build
        run: yarn build

      # - name: Move node_modules to dist
      #  run: mv node_modules dist/node_modules

      - name: Zip
        run: (cd dist && zip -r ../deploy.zip .)

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Created the Secrets Under the Repo only with These Variables
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to AWS
        run: aws lambda update-function-code --function-name=lambda-feedback-prod-pdf-generator --zip-file=fileb://deploy.zip
