name: Main deployment of pdf generator lambda function

on:
  push:
    branches: [main]

jobs:
  staging_job:
    name: Staging deployment of pdf generator lambda function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.LAMBDA_CONTAINER_PIPELINE_AWS_ID }}
          aws-secret-access-key: ${{ secrets.LAMBDA_CONTAINER_PIPELINE_AWS_SECRET }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the tagged docker image to Amazon ECR
        id: build-custom-image
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: lambda-feedback-staging-pdf-generator
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update aws custom lambda function code
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: lambda-feedback-staging-pdf-generator
          IMAGE_TAG: latest
        run: |
          aws lambda update-function-code \
              --function-name lambda-feedback-staging-pdf-generator \
              --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  prod_job:
    needs: staging_job
    name: Prod deployment of pdf generator lambda function
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: approval-team
          minimum-approvals: 1
          issue-title: "Deploying to prod"
          issue-body: "Please approve or deny the deployment"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ""
          additional-denied-words: ""

      - name: Build and push the tagged docker image to Amazon ECR
        id: build-custom-image
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: lambda-feedback-prod-pdf-generator
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update aws custom lambda function code
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: lambda-feedback-prod-pdf-generator
          IMAGE_TAG: latest
        run: |
          aws lambda update-function-code \
              --function-name lambda-feedback-prod-pdf-generator \
              --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
